package lehmer;

import java.math.*;
import java.math.BigInteger;

public class Frame2 extends javax.swing.JFrame {
    /** Creates new form Frame2 */

	public Frame2() {
        initComponents();
    }

	public Frame2(String input) {
        initComponents();
        calculate(input);
    }
	
	public void calculate(String s) {
      double landa = Double.parseDouble(s); // Lambda of Lehmer function
      long m = (long) Math.pow(2,31) - 1 ;  // m = 2^31 - 1   = 2,147,483,647
      long a = (long) Math.pow(2,7) - 1 ;   // a = 2^7 - 1    = 127
      int z0 = 4;
      String out="";
      
      // To calculate very big numbers
	  BigInteger temp1 = BigInteger.valueOf(0);
      BigInteger zn = BigInteger.valueOf(0);      
       
      String tos = "";
      double sn = 0;	// A double to be converted from String
      double ui = 0;	// U(i)
      double xi = 0 ;	// x(i)

    for (int idx = 1; idx <= 30; ++idx) {
        temp1 = BigInteger.valueOf(a).pow(idx).multiply(BigInteger.valueOf(4));
        // z(n) = (a^n * z0) mod m
		zn = temp1.mod(BigInteger.valueOf(m));
        tos = zn.toString();   			// BigIntegere conversion to String and then double
        sn = Double.parseDouble(tos);
        ui = (double) sn / m ;
        xi = - (1/landa) * Math.log(ui);
		out+=(ui+"\n\n");
    }

	jTextArea1.setText(out);
}
    
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Final Result");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Kamran", 1, 18));
        jLabel1.setText("Random variable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
